[Ilwis]
Description=Muestra la altura de las olas
Time=1652209848
Version=3.1
Class=Dependent Segment Map
ValueRangeChangeable=Yes
Type=BaseMap
[BaseMap]
CoordSystem=utm.csy
CoordBounds=-90.132 13.155 -87.684 14.451
Domain=value.dom
DomainInfo=value.dom;Long;value;0;-9999999.9:9999999.9:0.1:offset=0;
Range=-9999999.9:9999999.9:0.1:offset=0
HistogramSize=3
Type=SegmentMap
Proximity=0.006480
MinMax=18:20
Perc1=18:20
[SegmentMap]
Snap Distance=0.024480
Tunnel Width=0.002448
Type=SegmentMapVirtual
[IlwisObjectVirtual]
Expression=oleaje.altura
DefOnlyPossible=No
[ObjectDependency]
NrDepObjects=2
Object0=oleaje.mps
Object1=Column oleaje.altura
[SegmentMapVirtual]
Expression=oleaje.altura
Type=SegmentMapAttribute
[SegmentMapAttribute]
SegmentMap=oleaje.mps
AttribTable=oleaje.tbt
AttribColumn=altura
[SegmentMapStore]
Status=-32767
Format=2
Segments=3
DeletedSegments=0
Coordinates=0
[Table]
Description=
Time=1652209848
Version=3.1
Class=Table
Domain=None.dom
DomainInfo=none.dom;Byte;none;0;;
Columns=5
Records=3
Type=TableStore
[TableStore]
Data=altura_oleaje.mps#
UseAs=No
Col0=MinCoords
Col1=MaxCoords
Col2=Coords
Col3=Deleted
Col4=SegmentValue
Type=TableBinary
[Col:MinCoords]
Description=
Time=1652209848
Version=3.1
Class=Column
ValueRangeChangeable=Yes
Domain=utm.csy
DomainInfo=utm.csy;Coord;coord;0;;
ReadOnly=No
OwnedByTable=Yes
StoreType=Coord
Stored=Yes
Type=ColumnStore
[Col:MaxCoords]
Description=
Time=1652209848
Version=3.1
Class=Column
ValueRangeChangeable=Yes
Domain=utm.csy
DomainInfo=utm.csy;Coord;coord;0;;
ReadOnly=No
OwnedByTable=Yes
StoreType=Coord
Stored=Yes
Type=ColumnStore
[Col:Coords]
Description=
Time=1652209848
Version=3.1
Class=Column
ValueRangeChangeable=Yes
Domain=CoordBuf.dom
DomainInfo=CoordBuf.dom;?;coordbuf;0;;
ReadOnly=No
OwnedByTable=No
StoreType=CoordBuf
Stored=Yes
Type=ColumnStore
[Col:Deleted]
Description=
Time=1652209848
Version=3.1
Class=Column
ValueRangeChangeable=Yes
Domain=bool.dom
DomainInfo=bool.dom;Byte;bool;0;;
Range=0:1:offset=-1
ReadOnly=No
OwnedByTable=No
Sum=?
Mean=?
StdDev=?
StoreType=Long
Stored=Yes
Type=ColumnStore
[Col:SegmentValue]
Description=
Time=1652209848
Version=3.1
Class=Column
ValueRangeChangeable=Yes
Domain=value.dom
DomainInfo=value.dom;Long;value;0;-9999999.9:9999999.9:0.1:offset=0;
Range=-9999999.9:9999999.9:0.1:offset=0
ReadOnly=No
OwnedByTable=No
Sum=?
Mean=?
StdDev=?
StoreType=Long
Stored=Yes
Type=ColumnStore
